BenqOA/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Model;
using Model.Models;
using Public;

namespace BenqOA.Controllers
{
    //[MyAuthorFilter(Roles = MyAuthorFilter.LoginRole)]
    public class CommonController:Controller
    {
        //公有方法

        CommonDataBLL bll = new CommonDataBLL();

        /// <summary>
        /// 获取性别
        /// </summary>
        /// <returns></returns>
        public JsonResult GetSexInfo()
        {
            return Json(bll.GetSexInfo());
        }

        /// <summary>
        /// 获取职位
        /// </summary>
        /// <returns></returns>
        public JsonResult GetPosiInfo()
        {
            return Json(bll.GetPosiInfo());
        }

        /// <summary>
        /// 获取部门
        /// </summary>
        /// <returns></returns>
        public JsonResult GetDepInfo()
        {
            return Json(bll.GetDepInfo());
        }

        /// <summary>
        /// 获取角色
        /// </summary>
        /// <returns></returns>
        public JsonResult GetRoleInfo()
        {
            return Json(bll.GetRoleInfo());
        }

        /// <summary>
        /// 获取角色为部门经理的所有用户
        /// </summary>
        /// <returns></returns>
        public JsonResult GetPmUserCode()
        {
            CommonDataBLL bll = new CommonDataBLL();
            return Json(bll.GetPMUserCode());
        }

        /// <summary>
        /// 获取请假类型
        /// </summary>
        /// <returns></returns>
        public JsonResult GetLeaveType()
        {
            return Json(bll.GetLeaveType());
        }

        /// <summary>
        /// 获取公告类型
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAnnoType()
        {
            return Json(bll.GetAnnoType());
        }

        /// <summary>
        /// 文件类型
        /// </summary>
        /// <returns></returns>
        public JsonResult GetFileType()
        {
            CommonDataBLL bll = new CommonDataBLL();
            return Json(bll.GetFileType());
        }

        //根据请假类型ID获取请假类型名
        public ActionResult GetLeaveNameById(int Id)
        {
            //content 返回字符串
            ResultModel<object> resultModel = new ResultModel<object>();
            resultModel.Data = bll.GetLeaveNameById(Id);
            return Json(resultModel);
        }

        ////刚登录时把用户信息保存在session里
        //public ActionResult GetNav()
        //{
        //    User user = Session["userInfo"] as User;
        //    List<Permisson> list = null;
        //    using(var bqc=new BenqOAContext())
        //    {
        //        list = bqc.Permissons.OrderBy(m => m.PermSeq).ToList();
        //    }
        //    Session["NavInfo"] = list;
        //    return View();
        //}
    }
}

BenqOA/Controllers/SysManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using BenqOA.Helper;
using BLL;
using Model;
using Model.Models;
using Public;

namespace BenqOA.Controllers
{
    //[MyAuthorFilter(Roles = MyAuthorFilter.LoginRole)]  
    public class SysManageController : Controller
    {

        #region 用户管理
        /// <summary>
        /// 用户管理
        /// </summary>
        /// <returns></returns>
        [MyAuthorFilter(Roles = MyAuthorFilter.LoginRole)]
        public ActionResult UserManage()
        {
            return View();
        }

        /// <summary>
        /// 查询用户
        /// </summary>
        /// <param name="userCode">用户编号</param>
        /// <param name="realName">真实姓名</param>
        /// <param name="departmentCode">部门编号</param>
        /// <param name="pageindex">页面索引</param>
        /// <param name="pagesize">每页记录数</param>
        /// <returns></returns>
        public JsonResult UserManage_QueryUser(string userCode, string realName, string departmentCode, int pageindex, int pagesize)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.UserManage_QueryUser(userCode, realName, departmentCode, pageindex, pagesize));
        }

        /// <summary>
        /// 根据UserCode查询用户详细信息
        /// </summary>
        /// <param name="userCode">用户编号</param>
        /// <param name="pageAction">页面属性（编辑查看）</param>
        /// <returns></returns>
        public ActionResult UserManage_Detail(string userCode, string pageAction)
        {
            BenqOAContext bqc = new BenqOAContext();
            User model = new User();
            ViewBag.pageAction = pageAction;
            try
            {
                model = bqc.Users.FirstOrDefault(p => p.UserCode == userCode) as User;
                //密码解密显示
                model.UserPwd = EncryptAndDecrypt.DecryptDES(model.UserPwd, "stwhh123");
            }
            catch (Exception ee)
            {
                throw new Exception(ee.Message);
            }
            return View(model);
        }

        /// <summary>
        /// 添加用户页面
        /// </summary>
        /// <returns></returns>
        public ActionResult UserManage_AddUser()
        {
            return View();
        }

        /// <summary>
        /// 验证用户名是否存在
        /// </summary>
        /// <param name="userCode">用户编号</param>
        /// <returns></returns>
        public ActionResult CheckUserCode(string userCode)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.CheckUserCode(userCode), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 添加用户-保存
        /// </summary>
        /// <param name="user">用户实体</param>
        /// <returns></returns>
        public JsonResult UserManage_AddUser_Save(User user)
        {
            ResultModel<object> resultModel = new ResultModel<object>();
            using (var bqc = new BenqOAContext())
            {
                //bqc.Users.Add(user);  //方法1   --bqc.Users.Remove(user);删除
                User userSession = Session["userInfo"] as User; //获取session
                user.CreateUserCode = userSession.UserCode; //创建用户
                user.CreateTime = DateTime.Parse(DateTime.Now.ToString("yyyy-MM-dd")); //创建时间
                user.ModifyUserCode = userSession.UserCode; //修改用户
                user.ModifyTime = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd")); //修改时间

                //对密码进行加密
                user.UserPwd = EncryptAndDecrypt.EncryptDES(user.UserPwd, "stwhh123");
                try
                {
                    bqc.Entry(user).State = EntityState.Added; //方法2 在using System.Data命名空间下; 
                    bqc.SaveChanges();
                    resultModel.ErrorCode = "0";
                    resultModel.Message = "";

                }
                catch (Exception ee)
                {
                    resultModel.ErrorCode = "1";
                    resultModel.Message = ee.Message;
                }

            }

            return Json(resultModel);
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="userCode">用户编号</param>
        /// <returns></returns>
        public JsonResult UserManage_DelUser(string userCode)
        {
            //string ucode = Request.Params["userCode"].ToString(); //要使用此方法，前台不能以json格式传值，
            SysManageBll bll = new SysManageBll();
            return Json(bll.UserManage_DelUser(userCode));
        }

        /// <summary>
        /// 修改用户信息
        /// </summary>
        /// <param name="userNewInfo">用户实体</param>
        /// <returns></returns>
        public JsonResult UserManage_AlterUser(User userNewInfo)
        {
            ResultModel<object> resultModel = new ResultModel<object>();
            BenqOAContext bqc = new BenqOAContext();
            User userOldInfo = bqc.Users.FirstOrDefault(p => p.UserCode == userNewInfo.UserCode) as User;

            if (userOldInfo == null) return Json(resultModel);
            userOldInfo.RealName = userNewInfo.RealName;
            if (!string.IsNullOrEmpty(userNewInfo.UserPwd))
            {
                userOldInfo.UserPwd = EncryptAndDecrypt.EncryptDES(userNewInfo.UserPwd, "stwhh123"); //密码加密保存
            }
            try
            {
                userOldInfo.Sex = userNewInfo.Sex;
                userOldInfo.Age = userNewInfo.Age;
                userOldInfo.Phone = userNewInfo.Phone;
                userOldInfo.QQ = userNewInfo.QQ;
                userOldInfo.Email = userNewInfo.Email;
                userOldInfo.EntryDate = userNewInfo.EntryDate;
                userOldInfo.Address = userNewInfo.Address;
                userOldInfo.PositionCode = userNewInfo.PositionCode;
                userOldInfo.DepartmentCode = userNewInfo.DepartmentCode;
                userOldInfo.ModifyUserCode = userNewInfo.UserCode; //修改用户
                userOldInfo.ModifyTime = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd")); //修改时间

                //bqc.Entry(User).State = EntityState.Modified; //修改用户信息 修改可以不要这句
                bqc.SaveChanges();
                resultModel.ErrorCode = "0";
            }
            catch
            {
                resultModel.ErrorCode = "1";
                resultModel.Data = "";
            }

            return Json(resultModel);
        }

        #endregion


        #region 角色管理
        /// <summary>
        /// 角色管理页面
        /// </summary>
        /// <returns></returns>
        [MyAuthorFilter(Roles = MyAuthorFilter.LoginRole)]
        public ActionResult RoleManage()
        {
            return View();
        }

        /// <summary>
        /// 查询角色查询
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <param name="roleName">角色名称</param>
        /// <param name="pageindex">页面索引</param>
        /// <param name="pagesize">每页记录数</param>
        /// <returns></returns>
        public JsonResult RoleManage_Query(string roleCode, string roleName, int pageindex, int pagesize)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.RoleManage_Query(roleCode, roleName, pageindex, pagesize));
        }

        /// <summary>
        /// 根据角色编号查询所有属于这个角色的人员 User_Role-页面
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <returns></returns>
        public ActionResult RoleManage_User(string roleCode)
        {
            ViewBag.RoleCode = roleCode; //给页面其它方法调用
            return View();
        }

        /// <summary>
        /// 角色组用户页面--查询
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <param name="userCode">用户编号</param>
        /// <param name="realName">真实姓名</param>
        /// <returns></returns>
        public JsonResult Role_User_Query(string roleCode, string userCode, string realName)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.Role_User_Query(roleCode, userCode, realName));
        }

        /// <summary>
        /// 添加角色组用户页面
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <returns></returns>
        public ActionResult RoleManage_User_Add(string roleCode)
        {
            ViewBag.RoleCode = roleCode;
            return View();
        }

        //添加角色组用户-保存
        public ActionResult Role_AddUser_Save(string RoleCode, string selects)
        {
            ViewBag.RoleCode = RoleCode;
            SysManageBll bll = new SysManageBll();
            return Json(bll.Role_AddUser_Save(RoleCode, selects));
        }


        /// <summary>
        /// 删除角色组用户
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <param name="selects">选择的项</param>
        /// <returns></returns>
        public ActionResult DelRole_User(string roleCode, string selects)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.DelRole_User(roleCode, selects));
        }


        /// <summary>
        /// 查询不在当前角色组的所有用户-无分页
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <param name="userCode">用户编号</param>
        /// <param name="realName">真实姓名</param>
        /// <returns></returns>
        public JsonResult Role_QueryAllUser(string roleCode, string userCode, string realName)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.Role_QueryAllUser(roleCode, userCode, realName));
        }


        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="roleCode">角色编号</param>
        /// <returns></returns>
        public JsonResult RoleManage_DelRole(string roleCode)
        {
            SysManageBll bll = new SysManageBll();
            return Json(bll.RoleManage_DelRole(roleCode));

        }

        /// <summary>
        /// 新增角色页面
        /// </summary>

BenqOA/Views/SysManage/AlterPwd.cshtml
@{
    ViewBag.Title = "AlterPwd";
}

<h2>修改密码</h2>

<div class="panel panel-default">
@*    <div class="panel-heading">添加用户</div>*@
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input1">用户名</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="input1" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input2">用户名</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="input2" />
                        </div>
                    </div>
                    <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
                </form>
            </div>
        </div>
    </div>
</div>

BenqOA/Views/SysManage/DepaManage.cshtml
@{
    ViewBag.Title = "部门管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        查询条件
    </div>
    <div class="panel-body panel-block">
        <table class="searcharea">
            <tr>
                <td class="querylabel" style="width: 10%"><span>部门编号</span></td>
                <td style="width: 15%">
                    <input type="text" class="form-control" data-bind="value:DepartmentCode" /></td>
                <td class="querylabel" style="width: 10%"><span>部门名称</span></td>
                <td style="width: 15%">
                    <input type="text" class="form-control" data-bind="value:DepartmentName" /></td>
                <td class="querylabel" style="width: 10%"><span>部门经理</span></td>
                <td style="width: 15%">
                    <input type="text" class="form-control" data-bind="value:DepartmentManageCode" /></td>
                <td></td>
                <td>
                    <button type="button" class="btn btn-primary" onclick="Query()"><i class="icon-search"></i>查询</button>
                    <button type="button" class="btn btn-primary" onclick="Add()"><i class="icon-plus"></i>新增</button></td>
            </tr>
        </table>

    </div>
</div>

<div id="grid1" class="grid"></div>
<div class="space"></div>

<script type="text/javascript">
    var queryModel;
    function Init() {
        //自定义列
        var columns = [{
            headerTemplate: '删除',
            width: '30px',
            template: '<div class="iconcolor" onclick="Del(\'#=DepartmentCode#\')"><i class="icon-remove"></i></div>'
        },
        {
            headerTemplate: '编辑',
            width: '30px',
            template: '<div class="iconcolor" onclick="Edit(\'#=DepartmentCode#\')"><i class="icon-edit"></i></div>'
        },
       
        { field: 'DepartmentCode', title: '部门编号', width: '50px' },  //部门编号
        { field: 'DepartmentName', title: '部门名称', width: '50px' },  //部门名称
        { field: 'DepartmentManageCode', title: '部门经理', width: '50px' }  //部门名称
        ]

        //绑定上面对应的data-bind
        queryModel = {
            'DepartmentCode': ko.observable(''),
            'DepartmentName': ko.observable(''),
            'DepartmentManageCode': ko.observable('')
        }

        //绑定grid控件
        Grid_BindCheckBox('grid1', '/SysManage/DepaManage_Query', columns, queryModel);

        //应用绑定
        ko.applyBindings(queryModel);

    }


    //查询
    function Query() {
        Grid_Query('grid1');
    }

    //新增
    function Add() {
        View_ShowWindow_CallBack(240, 500, '新增部门', '/SysManage/DepaManage_Add', function () {
            Query();
        })
    }

    //删除
    function Del(DepartmentCode) {
        ShowConfirm("确定删除吗?", function () {
            $.ajax({
                url: 'DepaManage_Del',
                type: 'post',
                //contentType: 'appliation/json',
                //dataType: 'json',
                data: { "DepartmentCode": DepartmentCode },
                success: function (obj) {
                    if (obj.ErrorCode == "0") {
                        ShowAlert("删除成功", function () {
                            Query();
                        })
                    }
                    else {
                        ShowAlert("删除失败")
                    }
                }
            })
        }
        )
    }

    //编辑
    function Edit(DepartmentCode) {
        View_ShowWindow_CallBack(240, 500, '编辑角色', '/SysManage/DepaManage_Edit' + '?DepartmentCode=' + DepartmentCode, function () {
            Query();
        })
    }

    $(document).ready(function () {  //和 $(function(){ })一样
        Init();
    })

</script>

BenqOA/Views/SysManage/DepaManage_Add.cshtml
@{
    ViewBag.Title = "新增部门";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@Scripts.Render("~/Scripts/jqueryvalidate")
<link href="~/Content/Validate.css" rel="stylesheet" />

<div class="panel panel-default">

    <form id="form1" class="panel-body panel-block">
        <table class="searcharea">
            <tr>
                <td class="querylabel" style="width: 15%"><span>部门编号</span></td>
                <td style="width: 25%">
                    <input name="DepartmentCode" type="text" class="form-control" data-bind="value:DepartmentCode" placeholder="必填" /></td>
                <td class="querylabel" style="width: 15%"><span>部门名称</span></td>
                <td style="width: 25%">
                    <input name="DepartmentName" type="text" class="form-control" data-bind="value:DepartmentName" placeholder="必填" /></td>

            </tr>
            <tr>
                <td class="querylabel" style="width: 15%"><span>部门经理</span></td>
                <td style="width: 25%">
                    <input id="DepartmentManageCode" name="DepartmentManageCode" data-bind="value:DepartmentManageCode" placeholder="必填" style="width: 100%" /></td>
            </tr>
        </table>
    </form>
</div>

<div class="space"></div>
<div class="fullCenter">
    <button type="button" class="btn btn-primary" onclick="Save()"><i class="icon-save"></i>保存</button>
    <button type="button" class="btn btn-primary" onclick="Back()"><i class="icon-reply"></i>返回</button>
</div>

<script type="text/javascript">
    var queryModel;
    function Init() {

        //绑定上面对应的data-bind
        queryModel = {
            'DepartmentCode': ko.observable(''),
            'DepartmentName': ko.observable(''),
            'DepartmentManageCode': ko.observable('')
        }

        //绑定部门经理下拉框
        DropDownList_BindParameter('DepartmentManageCode', '@Url.Action("GetPmUserCode", "Common")', '', 'Text', 'Value');

        //应用绑定
        ko.applyBindings(queryModel);

        //把正则表达式加到jquery validate验证里
        $.validator.addMethod('regexp', function (value, element, param) {
            var reg = new RegExp(param);
            return this.optional(element) || reg.test(value);
        }, "");

        //1.验证数据 
        $('#form1').validate({
            rules: {
                DepartmentCode: {  //对应的name,不是ID
                    required: true,
                    remote: "CheckDepaCode" //验证部门编号是否被注册，
                }
            },
            messages: {
                DepartmentCode: {
                    remote: "部门编号已存在"
                }
            }
        })
    }

    //2.验证当前form下所有输入值是否合法
    function IsValidated(group) {
        var isValid = true;
        group.find(':input').each(function (i, item) {
            if (!$(item).valid()) {
                isValid = false;
                return isValid;
            }
        });
        return isValid;
    };

    //保存
    function Save() {
        if (IsValidated($('#form1'))) {
            $.ajax({
                type: 'post',
                url: '/SysManage/DepaManage_Add_Save',
                data: $('#form1').serialize(),//ko.toJSON(queryModel), jso格式数据要解析或使用模板引擎 jquery.tmpl.js
                success: function (result) {
                    if (result.ErrorCode == '0') {
                        ShowAlert('保存成功', null);
                    }
                }
            })
        }
    }

    //返回
    function Back() {
        View_CloseWindow();
    }

    $(document).ready(function () {  //和 $(function(){ })一样
        Init();
    })

</script>

BenqOA/Views/SysManage/UserManage_AddUser.cshtml
@{
    ViewBag.Title = "添加用户";
    Layout = "~/Views/Shared/_Layout2.cshtml";  /*_Layout2是弹出窗口模板页*/
}

@Scripts.Render("~/Scripts/jqueryvalidate")
<link href="~/Content/Validate.css" rel="stylesheet" />

<div class="panel panel-default">
    @*    <div class="panel-heading">添加用户</div>*@
    <div class="panel-body fullCenter" style="width: 80%">
        <div class="row ">
            <div class="col-xs-12">
                <form id="form1" class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="UserCode">用户编号</label>
                        <div class="col-xs-4">
                            <input id="UserCode" name="UserCode" type="text" class="form-control" data-bind="value:UserCode" placeholder="必填" />
                        </div>
                        <label class="col-xs-2 labelright" for="RealName">真实姓名</label>
                        <div class="col-xs-4">
                            <input id="RealName" name="RealName" type="text" class="form-control" data-bind="value:RealName" placeholder="必填" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="UserPwd">密码</label>
                        <div class="col-xs-4">
                            <input id="UserPwd" name="UserPwd" type="password" class="form-control" data-bind="value:UserPwd" placeholder="必填" />
                        </div>

                        <label class="col-xs-2 labelright" for="repeatUserPwd">确认密码</label>
                        <div class="col-xs-4">
                            <input id="repeatUserPwd" name="repeatUserPwd" type="password" class="form-control" placeholder="必填" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="Sex">性别</label>
                        <div class="col-xs-4">
                            <input id="Sex" name="Sex" data-bind="value:Sex" style="width: 100%" />
                        </div>
                        <label class="col-xs-2 labelright" for="Age">年龄</label>
                        <div class="col-xs-4">
                            <input id="Age" name="Age" type="text" class="form-control" data-bind="value:Age" placeholder="必填" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="Phone">手机</label>
                        <div class="col-xs-4">
                            <input id="Phone" type="text" name="Phone" class="form-control" data-bind="value:Phone" placeholder="必填" />
                        </div>
                        <label class="col-xs-2 labelright" for="QQ">QQ</label>
                        <div class="col-xs-4">
                            <input id="QQ" name="QQ" type="text" class="form-control" data-bind="value:QQ" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="Email">邮箱</label>
                        <div class="col-xs-4">
                            <input id="Email" name="Email" type="text" class="form-control" data-bind="value:Email" placeholder="必填" />
                        </div>
                        <label class="col-xs-2 labelright" for="EntryDate">入职时间</label>
                        <div class="col-xs-4">
                            <input id="EntryDate" name="EntryDate" data-bind="value:EntryDate" style="width: 100%;" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="Address">地址</label>
                        <div class="col-xs-4">
                            <input id="Address" name="Address" type="text" class="form-control" data-bind="value:Address" />
                        </div>

                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 labelright" for="PositionCode">职位</label>
                        <div class="col-xs-4">
                            <input id="PositionCode" name="PositionCode" data-bind="value:PositionCode" style="width: 100%" />
                        </div>
                        <label class="col-xs-2 labelright" for="DepartmentCode">所属部门</label>
                        <div class="col-xs-4">
                            <input id="DepartmentCode" name="DepartmentCode" data-bind="value:DepartmentCode" style="width: 100%" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="form-group fullCenter">
    <button type="button" class="btn btn-primary" onclick="Save()"><i class="icon-save"></i>保存</button>
    <button type="button" class="btn btn-primary" onclick="Back()"><i class="icon-reply"></i>返回</button>
</div>

<script type="text/javascript">
    var viewModel;
    function Init() {
        viewModel = {
            'UserCode': ko.observable(''),
            'RealName': ko.observable(''),
            'UserPwd': ko.observable(''),
            'Sex': ko.observable(''),
            'Age': ko.observable(''),
            'Phone': ko.observable(''),
            'QQ': ko.observable(''),
            'Email': ko.observable(''),
            'Address': ko.observable(''),
            'EntryDate': ko.observable('@DateTime.Now.ToString("yyyy-MM-dd")'), //日期控件赋初始值
            'PositionCode': ko.observable(''),
            'DepartmentCode': ko.observable('')
        }

        ////DropDownList 绑定自定义数据
        //var data = [
        //    { text: "男", value: "1" },
        //    { text: "女", value: "2" }
        //];

        //$('#ddlSex').kendoDropDownList({
        //    dataTextField: "text",
        //    dataValueField: "value",
        //    dataSource: data,
        //    index: 0
        //});

        //绑定下拉列表
        DropDownList_BindParameter('Sex', '@Url.Action("GetSexInfo", "Common")', '', 'Text', 'Value');
        DropDownList_BindParameter('PositionCode', '@Url.Action("GetPosiInfo", "Common")', '', 'Text', 'Value');
        DropDownList_BindParameter('DepartmentCode', '@Url.Action("GetDepInfo", "Common")', '', 'Text', 'Value');

        //绑定日期控件
        DatePicker_Bind("EntryDate");

        //绑定页面属性(必须放在最后一步)
        ko.applyBindings(viewModel);

        //把正则表达式加到jquery validate验证里
        $.validator.addMethod('regexp', function (value, element, param) {
            var reg = new RegExp(param);
            return this.optional(element) || reg.test(value);
        }, "");

        //1.验证数据 
        $('#form1').validate({
            rules: {
                UserCode: {  //对应的name,不是ID
                    required: true,
                    minlength: 3, //最少三个字符
                    maxlength: 10, //最多10个字符
                    remote: "CheckUserCode" //验证用户名是否被注册，调用control层CheckUserCode方法 为false时验证不通过，true时验证通过
                },
                RealName: {
                    required: true,
                    minlength: 2,
                    maxlength: 10
                },
                UserPwd: {
                    required: true,
                    minlength: 6,
                    maxlength: 12
                },
                repeatUserPwd: {
                    equalTo: "#UserPwd" //与原密码比较
                },
                Age: {
                    required: true,
                    //min: 0, //年龄最小值
                    //max:120
                    range: [0, 120]
                },
                Phone: {
                    required: true,
                    regexp: /^1\d{10}$/ //手机格式
                },
                QQ: {
                    regexp: /^\d{5,20}$/ //5-20位
                },
                Email: {
                    required: true,
                    email: true    //  邮箱的正则表达式/^([\da-zA-Z-_])+@@([\da-zA-Z-_])+(.[\da-zA-Z-_])$/
                },
                Address: {
                    rangelength: [5, 100]
                }
            },
            messages: {
                UserCode:{
                    remote:"该用户名已存在"
                },
                Phone: {
                    required: "不能为空",
                    regexp: "请输入正确的手机格式"
                },
                QQ: {
                    regexp: "5-20位"
                },
                Address: {
                    range: "5-100个字符"
                }
            }
        })
    }

    //2.验证当前form下所有输入值是否合法
    function IsValidated(group) {
        var isValid = true;
        group.find(':input').each(function (i, item) {
            if (!$(item).valid()) {
                isValid = false;
                return isValid;
            }
        });
        return isValid;
    };

    //3.保存前执行验证 保存
    function Save() {
        if (IsValidated($('#form1'))) {
            $.ajax({
                type: 'post',
                url: '/SysManage/UserManage_AddUser_Save',
                //contentType: 'application/json',
                //dataType: 'json',
                //如果以这种形式传值data:{'s':$('#form1').serialize()}，后台接收参数要用request.parms['']一个个接收
                data: $('#form1').serialize(),// ko.toJSON(viewModel),  //serialize()序列表表格内容为字符串,用于ajax接收。
                success: function (obj) {
                    if (obj.ErrorCode == '0') {
                        ShowAlert("保存成功")
                    }
                    else {
                        ShowAlert("保存失败")
                    }
                }
            })
        }
    }

    //返回（关闭）窗口
    function Back() {
        View_CloseWindow();
    }

    $(document).ready(function () {
        Init();

    })
</script>